# Generated by Django 5.2.16 on 2026-07-13 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='URL de la hoja de Google Sheets de donde se extraerán los datos.', max_length=500)),
                ('title', models.CharField(help_text='Título descriptivo del tablero.', max_length=255)),
                ('view_module', models.CharField(help_text="Nombre del módulo Python que contiene las vistas de los widgets (ej. 'ventas_norte' → views_ventas_norte.py).", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del tablero.')),
                ('user', models.ForeignKey(help_text='Usuario propietario del tablero.', on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WidgetInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título opcional que se muestra en la cabecera del widget.', max_length=255, null=True)),
                ('chart_type', models.CharField(choices=[('bar', 'Gráfico de Barras'), ('line', 'Gráfico de Líneas'), ('kpi', 'Tarjeta KPI'), ('filter', 'Filtro')], help_text='Tipo de gráfico o componente visual.', max_length=20)),
                ('function_name', models.CharField(help_text='Nombre de la función del servidor que ejecuta la consulta de datos para este widget.', max_length=255)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='JSON con todas las propiedades del frontend necesarias para renderizar el widget (ancho, alto, colores, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del widget.')),
                ('dashboard', models.ForeignKey(help_text='Tablero al que pertenece este widget.', on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='sheets_reports.dashboard')),
            ],
            options={
                'verbose_name': 'Widget Instance',
                'verbose_name_plural': 'Widget Instances',
                'ordering': ['created_at'],
            },
        ),
    ]
