# Generated by Django 5.2.16 on 2026-07-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='view_module',
        ),
        migrations.RemoveField(
            model_name='widgetinstance',
            name='function_name',
        ),
        migrations.AddField(
            model_name='widgetinstance',
            name='function_path',
            field=models.CharField(default='', help_text="Ruta a la función del servidor (ej. 'views_ventas_norte.total_ventas').", max_length=255),
        ),
    ]
