# Generated by Django 5.2.16 on 2026-07-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0002_remove_dashboard_view_module_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widgetinstance',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Widget Instance', 'verbose_name_plural': 'Widget Instances'},
        ),
        migrations.AddField(
            model_name='widgetinstance',
            name='order',
            field=models.IntegerField(default=0, help_text='Orden del widget en el lienzo (posición).'),
        ),
    ]
