# Generated by Django 5.2.16 on 2026-07-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0003_alter_widgetinstance_options_widgetinstance_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único usado en la URL del tablero, generado a partir del título.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='widgetinstance',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Gráfico de Barras'), ('line', 'Gráfico de Líneas'), ('kpi', 'Tarjeta KPI'), ('filter', 'Filtro'), ('table', 'Tabla')], help_text='Tipo de gráfico o componente visual.', max_length=20),
        ),
    ]
