# Generated by Django 5.2.16 on 2026-07-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0005_backfill_dashboard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetinstance',
            name='function_path',
            field=models.CharField(default='', help_text="Nombre de la función del servidor definida en server_functions/<slug del tablero>/functions.py (ej. 'total_ventas').", max_length=255),
        ),
    ]
