# Generated by Django 5.2.16 on 2026-07-16 01:56

from django.db import migrations, models


def backfill_functions_slug(apps, schema_editor):
    Dashboard = apps.get_model('sheets_reports', 'Dashboard')
    for dashboard in Dashboard.objects.filter(functions_slug__isnull=True).order_by('id'):
        dashboard.functions_slug = dashboard.slug
        dashboard.save(update_fields=['functions_slug'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0006_alter_widgetinstance_function_path_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='functions_slug',
            field=models.SlugField(blank=True, help_text='Identificador interno y permanente usado para ubicar server_functions/<functions_slug>/. Se genera una sola vez al crear el tablero y nunca cambia, aunque se edite el título.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único usado en la URL del tablero, generado a partir del título. Se actualiza cada vez que cambia el título.', max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(backfill_functions_slug, noop),
    ]
