# Generated by Django 5.2.16 on 2026-07-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0007_dashboard_functions_slug_alter_dashboard_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetinstance',
            name='code',
            field=models.TextField(blank=True, default='', help_text='Código Python ejecutado por el widget (debe definir `def run(request, widget):` que retorna un JsonResponse). Si está vacío, se usa function_path.'),
        ),
        migrations.AddField(
            model_name='widgetinstance',
            name='prompt',
            field=models.TextField(blank=True, default='', help_text='Último prompt en lenguaje natural usado para generar `code` vía IA.'),
        ),
        migrations.AlterField(
            model_name='widgetinstance',
            name='function_path',
            field=models.CharField(default='', help_text="Nombre de la función del servidor definida en server_functions/<slug del tablero>/functions.py (ej. 'total_ventas'). Se usa solo si `code` está vacío.", max_length=255),
        ),
    ]
