# Generated by Django 5.2.16 on 2026-07-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0008_widgetinstance_code_widgetinstance_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='shared_code',
            field=models.TextField(blank=True, default='', help_text='Código Python compartido por todos los widgets del tablero (funciones reutilizables, ej. columnas calculadas). Se inyecta en el exec() de cada widget antes de su propio código.'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='shared_code_prompt',
            field=models.TextField(blank=True, default='', help_text='Último prompt usado para generar shared_code vía IA.'),
        ),
    ]
