# Generated by Django 5.2.16 on 2026-07-19 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0009_dashboard_shared_code_dashboard_shared_code_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardUtilFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Personalizada', max_length=50)),
                ('source_code', models.TextField()),
                ('created_from_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_utils', to='sheets_reports.dashboard')),
            ],
            options={
                'verbose_name': 'Función Utilitaria del Tablero',
                'verbose_name_plural': 'Funciones Utilitarias del Tablero',
                'ordering': ['category', 'name'],
                'unique_together': {('dashboard', 'name')},
            },
        ),
    ]
