# Generated by Django 5.2.16 on 2026-07-19 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0011_split_shared_code_into_util_functions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='shared_code',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='shared_code_prompt',
        ),
    ]
