# Generated by Django 5.2.16 on 2026-07-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0012_remove_shared_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='functions_slug',
        ),
        migrations.RemoveField(
            model_name='widgetinstance',
            name='function_path',
        ),
        migrations.AlterField(
            model_name='widgetinstance',
            name='code',
            field=models.TextField(blank=True, default='', help_text='Código Python ejecutado por el widget (debe definir `def run(request, widget):` que retorna un JsonResponse).'),
        ),
    ]
