# Generated by Django 5.2.16 on 2026-07-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0013_remove_dashboard_functions_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetinstance',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Gráfico de Barras'), ('line', 'Gráfico de Líneas'), ('donut', 'Gráfico de Dona'), ('kpi', 'Tarjeta KPI'), ('filter', 'Filtro'), ('table', 'Tabla')], help_text='Tipo de gráfico o componente visual.', max_length=20),
        ),
    ]
