# Generated by Django 5.2.16 on 2026-07-26 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0014_alter_widgetinstance_chart_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='OBSOLETO: URL de Google Sheets, reemplazado por `data_source`. Se conserva temporalmente solo para el fallback de lectura durante la migración a DataSource.', max_length=500),
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre descriptivo de esta conexión (ej. 'Ventas - Postgres prod').", max_length=255)),
                ('source_type', models.CharField(choices=[('google_sheets', 'Google Sheets'), ('postgres', 'PostgreSQL')], help_text='Tipo de origen de datos; determina qué conector (sheets_reports.connectors) lo interpreta.', max_length=30)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuración específica del tipo de origen (URL de sheet, credenciales de Postgres, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Usuario propietario de esta conexión.', on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Origen de Datos',
                'verbose_name_plural': 'Orígenes de Datos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='data_source',
            field=models.ForeignKey(blank=True, help_text='Origen de datos de este tablero.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboards', to='sheets_reports.datasource'),
        ),
    ]
