# Generated by Django 5.2.16 on 2026-09-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0016_backfill_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetinstance',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Resumen breve, en lenguaje no técnico, generado por IA, de qué muestra este widget (usado como tooltip). Se limpia y se regenera automáticamente cada vez que `code` cambia; ver widget_dispatcher.dispatch_widget.'),
        ),
    ]
