# Generated by Django 5.2.16 on 2026-09-10 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_reports', '0017_widgetinstance_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(help_text="Nombre calificado de la tabla, ej. 'google_sheets__Respuestas'.", max_length=255)),
                ('column_name', models.CharField(help_text="Nombre de la columna resultante, ej. 'Nivel'.", max_length=100)),
                ('expression', models.TextField(help_text='Expresión SQL de DuckDB (ej. un CASE WHEN), usable dentro de SELECT (expr) AS col.')),
                ('description', models.TextField(blank=True)),
                ('created_from_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_columns', to='sheets_reports.datasource')),
            ],
            options={
                'verbose_name': 'Columna Calculada',
                'verbose_name_plural': 'Columnas Calculadas',
                'ordering': ['table_name', 'column_name'],
                'unique_together': {('data_source', 'table_name', 'column_name')},
            },
        ),
    ]
